[versions]
agp = "8.3.0"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
jetbrainsKotlinJvm = "1.9.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
autoservice = { group = "com.google.auto.service", name = "auto-service", version = "1.0-rc3" }
javapoet = { group = "com.squareup", name = "javapoet", version = "1.11.1" }
commons-text = { group = "org.apache.commons", name = "commons-text", version = "1.1" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }

# Testing
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.10.0" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version = "2.21.0" }
compiletesting = { group = "com.google.testing.compile", name = "compile-testing", version = "0.15" }
guava = { group = "com.google.guava", name = "guava", version = "23.5-jre" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

